# Generated by Django 4.2.20 on 2025-04-09 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavorite',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='character',
        ),
        migrations.AddField(
            model_name='character',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='api.character')),
            ],
        ),
    ]
