# Generated by Django 4.2.20 on 2025-04-11 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_added_at_userfavorite_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brawler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('rarity', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('title', models.CharField(blank=True, max_length=100)),
                ('brawler_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.role')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('brawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='api.brawler')),
            ],
        ),
        migrations.CreateModel(
            name='Super',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('brawler', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='super', to='api.brawler')),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('brawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='api.brawler')),
            ],
        ),
        migrations.DeleteModel(
            name='Ability',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='character',
        ),
        migrations.RemoveField(
            model_name='userfavorite',
            name='character',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.AddField(
            model_name='brawler',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category'),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='brawler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.brawler'),
            preserve_default=False,
        ),
    ]
