# Generated by Django 4.2.20 on 2025-04-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_brawler_category_fact_super_tip_delete_ability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brawler',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brawler',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
