# Generated by Django 4.2.20 on 2025-04-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_brawler_description_alter_brawler_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='brawler',
            name='super_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brawler',
            name='super_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Super',
        ),
    ]
